---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[test_stunnel::default]
  - name: certificates
    run_list:
      - recipe[test_stunnel::certificates]
