name             'stunnel'
maintainer       'Sous-Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Provides resources to help install and configure stunnel'
source_url       'https://github.com/sous-chefs/chef-stunnel'
issues_url       'https://github.com/sous-chefs/chef-stunnel/issues'
version          '4.0.0'
chef_version     '>= 13'

supports 'ubuntu'
supports 'centos'
supports 'fedora'
supports 'suse'

depends 'build-essential'
