name             'stunnel'
maintainer       'Aetrion, LLC.'
maintainer_email 'ops@dnsimple.com'
license          'Apache 2.0'
description      'Provides resources to help install and configure stunnel'
source_url       'https://github.com/aetrion/chef-stunnel'
issues_url       'https://github.com/aetrion/chef-stunnel/issues'
version          '2.1.0'

depends 'build-essential'
